chore: remove acorn
ShaunSHamilton/web3 pull request #97
Opened 2023-05-01 19:06 UTC by gikf

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #93

2023-05-01 19:22 UTC, ShaunSHamilton requested changes

2023-05-01 19:22 UTC, ShaunSHamilton commented on curriculum/locales/english/learn-digital-ledgers-by-building-a-blockchain.md
Thanks for tackling this ⭐ 

One issue is the assertion messages. A Camper who does not know Babel's AST, an assertion of `expected "CallExpression" to equal "ObjectExpress"` is not useful. The reason this is important is there are multiple assertions within one test, so the specific place this fails is useful.

As such, it would be ideal for the assertions to have custom messages. As a reference: https://github.com/freeCodeCamp/solana-curriculum/blob/main/curriculum/locales/english/learn-solanas-token-program-by-minting-a-fungible-token.md

Following the above as reference, notice the messages specifically do not follow the general freeCodeCamp "second-person voice". These are supposed to be technical additions/information.

2023-05-02 09:49 UTC, ShaunSHamilton approved these changes
LGTM 👍 

I do not think the version bump is necessary, though, but it does not matter much.

2023-05-12 02:47 UTC, moT01 approved these changes
LGTM 🎉 Thanks @gikf 🎉

2023-05-12 02:47 UTC, merged